services:
  db:
    image: postgis/postgis:15-3.3
    container_name: monitoreo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: monitoreo_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - /var/www/maps:/app/maps
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-postgres}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    restart: always

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: monitoreo_tileserver
    volumes:
      - /var/www/maps:/data
    ports:
      - "8080:8080"
    command: [ "-p", "8080", "--mbtiles", "colombia.mbtiles" ]
    restart: always

volumes:
  postgres_data:
