services:
  db:
    image: postgis/postgis:15-3.3
    container_name: monitoreo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoreo_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../maps:/app/maps
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-monitoreo}:${POSTGRES_PASSWORD:-monitoreo123}@db:5432/${POSTGRES_DB:-monitoreodb}
    restart: always

volumes:
  postgres_data:
